### PR TITLE
return dfs

### PR DESCRIPTION
**Pull request by knaaptime**
this enables a more consistent API by ensuring that the interpolation functions all return geodataframes with the target geometry

### CODE REVIEW

**Comment by renanxcortes** [comment]
Agreed that this makes more sense

**Comment by renanxcortes** [comment]
The gdf was adding a bug in the values?

**Comment by knaaptime** [comment]
instead of returning the full target df with interpolated values as an additional column, this will return a smaller df with only the interpolated variable and geometry

**Comment by knaaptime** [comment]
tests are passing locally but having trouble locating the raster data on quilt

**Pull request merged**
