### PR TITLE
[WIP] start kriging module

### PR DESCRIPTION
**Pull request by knaaptime**
this is a first draft at adding a kriging module based on [pykrige](https://geostat-framework.readthedocs.io/projects/pykrige/en/stable/). Initial explorations were pretty positive, though the quality of the interpolation obviously depends a great deal on the variogram fit

### CODE REVIEW

**Comment by knaaptime** [comment]
currently this is just to get started exploring the mechanics of the external libraries. The first fraft takes a *really* naive approach assigning the predicted value for the target_df centroid to the whole polygon. Instead, we should probably generate a geocube raster of the prediction surface then allow both (a) averaging of pixel values inside the polygon and (b) proper [block kriging](https://link.springer.com/content/pdf/10.1007/978-1-4615-5001-3_12.pdf)

**Comment by sjsrey** [comment]
I think we need to consider different treatments for the extensive and intensive variables. At first glance, kriging seems more appropriate for the latter.

**Review by sjsrey — COMMENTED** [review]
I think we need to consider different treatments for the extensive and intensive variables. At first glance, kriging seems more appropriate for the latter.

**Comment by knaaptime** [comment]
agreed on both.

i've also played around a bit further and there are a few different ways we could go about this (and maybe provide options for more than one). The question is how we want to shoehorn the very discrete process of human geography into a continuous spatial model (though as you said, it should work reasonably for percentages).

1. (in the current PR) is the simplest (probably overly so). It estimates the model using polygon centroids from source_df as observations, then uses that model to predict values at the centroids of target_df. The issue here is that, especially for extensive variables like counts, we end up wayy overestimating the volume of the total surface (so that implementation also includes a rescale). We dont have "control" observations in places with 0 population, so the estimated surface doesn't have the variation we need it to have
2. Estimate the model using source_df centroids, then estimate a continuous raster, then take the average of pixel values that fall inside target_df polygons. I think this is closer to the spirit of block kriging, though still looking for the best reference
3. Rasterize input_df and estimate the model using that raster, then estimate a continuous raster and take the average within target_df polys. This might help capture some of the "harder" edges between polygons that get overly smoothed in approach (1), but also kind of inflates the data (estimating raster resolution x polygon area "observations" instead of one per polygon) so might end up with some oddities for places with lots of heterogeneously-sized polygons. This is also really computationally intensive because the training data becomes so large, so a hybrid option of sorts might be to use something like pointpats to drop random points inside each polygon and use those as observations

**Comment by knaaptime** [comment]
actually, a 4th option riffing on 3, would be to include auxiliary data to mask out uninhabited regions of source_df, then randomly drop points in the inhabited areas and assign them them values from source_df, then in uninhabited areas drop random points and assign them all 0 and estimate on that "surface"

**Comment by knaaptime** [comment]
https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1538-4632.2004.tb01135.x

**Pull request closed without merging**
