### PR TITLE
more efficient unary_union in h3fy

### PR DESCRIPTION
**Pull request by knaaptime**

### CODE REVIEW

**Comment by martinfleis** [comment]
This does not help in case of multipolygons. We do unary_union, then fail -> `except:` and do it again.

I'd do unary_union, save it separately and pass it directly to `_to_hex` and that loop in case of multipolygon instead of passing gdf.

**Comment by knaaptime** [comment]
gotcha. the new strategy should handle it this way

**Comment by martinfleis** [comment]
Hey @knaaptime, I have pushed a bit of a cleanup. There's no need to go via geopandas, explode and such in this. Feel free to revert if you don't like this way but it seems to be cleaner and more straightforward to my eyes like this.

**Comment by knaaptime** [comment]
excellent, thank you! I was just in the middle of doing a portion of this because my crs handling was ridiculous. Looking at the code for too long and jumping through too many hoops :)

**Review by martinfleis — APPROVED** [review]

**Comment by knaaptime** [comment]
@martinfleis i had to move the clip up above the reprojection otherwise the gdfs are misaligned, otherwise i think this is set

**Pull request merged**
